[package]
name = "mouse"
version = "0.1.0"
authors = ["Cory Forsstrom <cforsstrom18@gmail.com>"]
edition = "2018"


[dependencies]
anyhow = "1.0"
byteorder = "1.3"
env_logger = "0.7"
hidapi = "1.2.2"
log = "0.4"
thiserror = "1.0"